version: "3.8"
services:
  postgres:
    # image: postgres:15 - not supported in docker compose v2
    container_name: skincare-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: skincare
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
